import { Bot, InlineKeyboard } from 'grammy';
import { adjustBalance, approveTopup, createTopupRequest, getBalanceHistory, getOrderDetails, getStats, getUserProfile, listPendingTopups, listRecentOrders, listUserOrders, listUsers, rejectTopup, setOrderStatus, upsertUser } from './db.js';

const token=process.env.BOT_TOKEN;
if(!token) throw new Error('BOT_TOKEN is required');
export const bot=new Bot(token);
const adminIds=new Set((process.env.ADMIN_IDS||'').split(',').map(x=>Number(x.trim())).filter(Boolean));
const webAppUrl=process.env.WEB_APP_URL||'';
const contact=process.env.CONTACT_USERNAME||'elotonieja';
const money=c=>`${(Number(c||0)/100).toFixed(2).replace('.',',')} zł`;
const isAdmin=ctx=>adminIds.has(ctx.from?.id);
const labels={new:'nowe',processing:'w realizacji',ready:'gotowe',completed:'zakończone',cancelled:'anulowane'};

function mainKeyboard(){const k=new InlineKeyboard();if(webAppUrl)k.webApp('🛍 Otwórz sklep',webAppUrl).row();return k.text('📦 Moje zamówienia','orders').row().text('👤 Profil','profile').text('💬 Kontakt','contact');}
function profileKeyboard(){return new InlineKeyboard().text('💳 Doładuj saldo','topup').row().text('💰 Historia salda','balance_history').row().text('⬅️ Cofnij','home');}
function ordersKeyboard(){return new InlineKeyboard().text('🔄 Odśwież','orders').row().text('⬅️ Cofnij','home');}
function adminKeyboard(){return new InlineKeyboard().text('📦 Zamówienia','admin_orders').row().text('👥 Użytkownicy','admin_users').text('💳 Salda','admin_balances').row().text('📊 Statystyki','admin_stats').row().text('⬅️ Cofnij','home');}
function topupKeyboard(){return new InlineKeyboard().text('20 zł','topup:2000').text('50 zł','topup:5000').text('100 zł','topup:10000').row().text('200 zł','topup:20000').row().text('⬅️ Cofnij','profile');}
function pendingTopupKeyboard(rows){const k=new InlineKeyboard();for(const r of rows){k.text(`✅ #${r.id} +${money(r.amount_cents)}`,`topup_approve:${r.id}`).text('❌ Odrzuć',`topup_reject:${r.id}`).row();}return k.text('⬅️ Panel admina','admin');}
async function safeEdit(ctx,text,reply_markup){try{await ctx.editMessageText(text,{parse_mode:'Markdown',reply_markup});}catch(e){if(!String(e?.description||e).includes('message is not modified'))throw e;}}
async function notifyStatus(userId,orderId,status,total){try{await bot.api.sendMessage(Number(userId),`📦 *Zamówienie #${orderId}*\n\nStatus: *${labels[status]||status}*\nKwota: ${money(total)}`,{parse_mode:'Markdown'});}catch(e){console.error('Status notification error:',e);}}
async function showAdminBalances(ctx){const rows=await listPendingTopups(15);const text=rows.length?`💳 *Oczekujące doładowania*\n\n${rows.map(r=>`#${r.id} • ${money(r.amount_cents)} • @${r.username||'brak'}`).join('\n')}\n\nWybierz poniżej zatwierdzenie albo odrzucenie.`:'💳 *Salda*\n\nBrak oczekujących doładowań.';await safeEdit(ctx,text,pendingTopupKeyboard(rows));}

bot.use(async(ctx,next)=>{if(ctx.from)await upsertUser(ctx.from);await next();});
bot.command('start',async ctx=>{try{await ctx.deleteMessage();}catch{}await ctx.reply('🖤 *La Familia*\n\nWybierz opcję:',{parse_mode:'Markdown',reply_markup:mainKeyboard()});});
bot.command('help',ctx=>ctx.reply('/start – menu\n/orders – moje zamówienia\n/profile – profil\n\nAdministrator: /admin, /status ID STATUS, /balance ID KWOTA'));
async function showProfile(ctx){const p=await getUserProfile(ctx.from.id);const username=p?.username?`@${p.username}`:'Brak nicku';await safeEdit(ctx,`👤 *Profil*\n\n🆔 ID użytkownika: \`${p?.id||ctx.from.id}\`\n🏷 Nick: ${username}\n💰 Saldo: *${money(p?.balance_cents)}*\n✅ Udane zamówienia: *${p?.successful_orders||0}*`,profileKeyboard());}
async function showOrders(ctx){const orders=await listUserOrders(ctx.from.id);const k=new InlineKeyboard();for(const o of orders.slice(0,10))k.text(`#${o.id} • ${labels[o.status]||o.status} • ${money(o.total_cents)}`,'order:'+o.id).row();k.text('🔄 Odśwież','orders').row().text('⬅️ Cofnij','home');const text=orders.length?'📦 *Moje zamówienia*\n\nWybierz zamówienie, aby zobaczyć szczegóły.':'📦 *Moje zamówienia*\n\nNie masz jeszcze żadnych zamówień.';await safeEdit(ctx,text,k);}
async function showOrderDetails(ctx,id){const d=await getOrderDetails(id,ctx.from.id);if(!d)return ctx.answerCallbackQuery({text:'Nie znaleziono zamówienia.',show_alert:true});const items=d.items.map(i=>`• ${i.name} × ${i.quantity} — ${money(Number(i.price_cents)*Number(i.quantity))}`).join('\n')||'Brak pozycji';const o=d.order;await safeEdit(ctx,`📦 *Zamówienie #${o.id}*\n\nStatus: *${labels[o.status]||o.status}*\nData: ${new Date(o.created_at).toLocaleString('pl-PL')}\nKwota: *${money(o.total_cents)}*\n\n*Produkty:*\n${items}`,new InlineKeyboard().text('🔄 Odśwież','order:'+o.id).row().text('⬅️ Zamówienia','orders'));}
async function showBalanceHistory(ctx){const rows=await getBalanceHistory(ctx.from.id);const text=rows.length?`💰 *Historia salda*\n\n${rows.map(r=>`${Number(r.amount_cents)>=0?'🟢':'🔴'} ${Number(r.amount_cents)>=0?'+':''}${money(r.amount_cents)} • ${r.type} • ${new Date(r.created_at).toLocaleDateString('pl-PL')}`).join('\n')}`:'💰 *Historia salda*\n\nBrak operacji.';await safeEdit(ctx,text,new InlineKeyboard().text('⬅️ Cofnij','profile'));}

bot.callbackQuery('home',async ctx=>{await ctx.answerCallbackQuery();await safeEdit(ctx,'🖤 *La Familia*\n\nWybierz opcję:',mainKeyboard());});
bot.callbackQuery('profile',async ctx=>{try{await showProfile(ctx);await ctx.answerCallbackQuery();}catch(e){console.error('Profile error:',e);await ctx.answerCallbackQuery({text:'Nie udało się wczytać profilu.',show_alert:true});}});
bot.callbackQuery('orders',async ctx=>{try{await showOrders(ctx);await ctx.answerCallbackQuery();}catch(e){console.error('Orders error:',e);await ctx.answerCallbackQuery({text:'Nie udało się wczytać zamówień.',show_alert:true});}});
bot.callbackQuery(/^order:(\d+)$/,async ctx=>{try{await showOrderDetails(ctx,Number(ctx.match[1]));await ctx.answerCallbackQuery();}catch(e){console.error('Order details error:',e);await ctx.answerCallbackQuery({text:'Nie udało się wczytać zamówienia.',show_alert:true});}});
bot.callbackQuery('balance_history',async ctx=>{try{await showBalanceHistory(ctx);await ctx.answerCallbackQuery();}catch(e){console.error(e);await ctx.answerCallbackQuery({text:'Nie udało się pobrać historii.',show_alert:true});}});
bot.callbackQuery('topup',async ctx=>{await ctx.answerCallbackQuery();await safeEdit(ctx,'💳 *Doładuj saldo*\n\nWybierz kwotę. Zostanie utworzona prośba o doładowanie do zatwierdzenia przez administratora.',topupKeyboard());});
bot.callbackQuery(/^topup:(\d+)$/,async ctx=>{const amount=Number(ctx.match[1]);try{const id=await createTopupRequest(ctx.from.id,amount);await ctx.answerCallbackQuery({text:`Prośba #${id} utworzona`});await safeEdit(ctx,`💳 *Doładowanie #${id}*\n\nKwota: *${money(amount)}*\nStatus: ⏳ oczekuje na potwierdzenie administratora.`,new InlineKeyboard().text('⬅️ Cofnij','profile'));}catch(e){console.error(e);await ctx.answerCallbackQuery({text:'Nie udało się utworzyć prośby.',show_alert:true});}});
bot.callbackQuery('contact',async ctx=>{await ctx.answerCallbackQuery();await safeEdit(ctx,`💬 *Kontakt*\n\nTelegram: @${contact}`,new InlineKeyboard().text('⬅️ Cofnij','home'));});

async function showAdmin(ctx){if(!isAdmin(ctx)){if(ctx.callbackQuery)return ctx.answerCallbackQuery({text:'Brak uprawnień.',show_alert:true});return ctx.reply('Brak uprawnień.');}if(ctx.callbackQuery){await ctx.answerCallbackQuery();await safeEdit(ctx,'🛠 *Panel administratora*\n\nWybierz sekcję:',adminKeyboard());}else{try{await ctx.deleteMessage();}catch{}await ctx.reply('🛠 *Panel administratora*\n\nWybierz sekcję:',{parse_mode:'Markdown',reply_markup:adminKeyboard()});}}
bot.command('admin',showAdmin);
bot.callbackQuery('admin',showAdmin);
bot.callbackQuery('admin_orders',async ctx=>{if(!isAdmin(ctx))return ctx.answerCallbackQuery({text:'Brak uprawnień.',show_alert:true});const rows=await listRecentOrders(10);const text=rows.length?`📦 *Ostatnie zamówienia*\n\n${rows.map(o=>`#${o.id} • ${labels[o.status]||o.status} • ${money(o.total_cents)} • @${o.username||'brak'}`).join('\n')}`:'Brak zamówień.';await ctx.answerCallbackQuery();await safeEdit(ctx,text,new InlineKeyboard().text('⬅️ Panel admina','admin'));});
bot.callbackQuery('admin_users',async ctx=>{if(!isAdmin(ctx))return ctx.answerCallbackQuery({text:'Brak uprawnień.',show_alert:true});const rows=await listUsers(15);const text=rows.length?`👥 *Użytkownicy*\n\n${rows.map(u=>`🆔 ${u.id} • @${u.username||'brak'} • ${money(u.balance_cents)} • zamówienia: ${u.orders_count}`).join('\n')}`:'Brak użytkowników.';await ctx.answerCallbackQuery();await safeEdit(ctx,text,new InlineKeyboard().text('⬅️ Panel admina','admin'));});
bot.callbackQuery('admin_balances',async ctx=>{if(!isAdmin(ctx))return ctx.answerCallbackQuery({text:'Brak uprawnień.',show_alert:true});try{await ctx.answerCallbackQuery();await showAdminBalances(ctx);}catch(e){console.error('Admin balances error:',e);await ctx.answerCallbackQuery({text:'Nie udało się pobrać doładowań.',show_alert:true});}});
bot.callbackQuery('admin_stats',async ctx=>{if(!isAdmin(ctx))return ctx.answerCallbackQuery({text:'Brak uprawnień.',show_alert:true});const s=await getStats();await ctx.answerCallbackQuery();await safeEdit(ctx,`📊 *Statystyki*\n\n👥 Użytkownicy: *${s.users}*\n📦 Zamówienia: *${s.orders}*\n✅ Zakończone: *${s.completed}*\n💰 Obrót zakończonych: *${money(s.revenue)}*`,new InlineKeyboard().text('⬅️ Panel admina','admin'));});

bot.callbackQuery(/^topup_approve:(\d+)$/,async ctx=>{if(!isAdmin(ctx))return ctx.answerCallbackQuery({text:'Brak uprawnień.',show_alert:true});const id=Number(ctx.match[1]);try{const r=await approveTopup(id);if(!r)return ctx.answerCallbackQuery({text:'Ta prośba jest już rozpatrzona.',show_alert:true});await ctx.answerCallbackQuery({text:`Doładowanie #${id} zatwierdzone`});try{await bot.api.sendMessage(Number(r.user_id),`💳 *Doładowanie potwierdzone*\n\n+${money(r.amount_cents)}\nSaldo zostało zaktualizowane.`,{parse_mode:'Markdown'});}catch{}await showAdminBalances(ctx);}catch(e){console.error('Topup approve error:',e);await ctx.answerCallbackQuery({text:'Nie udało się zatwierdzić.',show_alert:true});}});
bot.callbackQuery(/^topup_reject:(\d+)$/,async ctx=>{if(!isAdmin(ctx))return ctx.answerCallbackQuery({text:'Brak uprawnień.',show_alert:true});const id=Number(ctx.match[1]);try{const r=await rejectTopup(id);if(!r)return ctx.answerCallbackQuery({text:'Ta prośba jest już rozpatrzona.',show_alert:true});await ctx.answerCallbackQuery({text:`Doładowanie #${id} odrzucone`});try{await bot.api.sendMessage(Number(r.user_id),'❌ *Doładowanie odrzucone*\n\nProśba o doładowanie nie została zaakceptowana.',{parse_mode:'Markdown'});}catch{}await showAdminBalances(ctx);}catch(e){console.error('Topup reject error:',e);await ctx.answerCallbackQuery({text:'Nie udało się odrzucić.',show_alert:true});}});

bot.command('status',async ctx=>{if(!isAdmin(ctx))return ctx.reply('Brak uprawnień.');const p=ctx.message.text.trim().split(/\s+/);const id=Number(p[1]),status=p[2];if(!id||!['new','processing','ready','completed','cancelled'].includes(status))return ctx.reply('Użycie: /status ID new|processing|ready|completed|cancelled');const r=await setOrderStatus(id,status);if(!r)return ctx.reply(`Nie znaleziono #${id}.`);await notifyStatus(r.user_id,r.id,r.status,r.total_cents);await ctx.reply(`✅ Zamówienie #${id}: ${labels[status]||status}`);});
bot.command('topupapprove',async ctx=>{if(!isAdmin(ctx))return;try{await ctx.deleteMessage();}catch{}const id=Number(ctx.message.text.trim().split(/\s+/)[1]);const r=await approveTopup(id);if(!r)return;});
bot.command('topupreject',async ctx=>{if(!isAdmin(ctx))return;try{await ctx.deleteMessage();}catch{}const id=Number(ctx.message.text.trim().split(/\s+/)[1]);await rejectTopup(id);});
bot.command('balance',async ctx=>{if(!isAdmin(ctx))return ctx.reply('Brak uprawnień.');const p=ctx.message.text.trim().split(/\s+/);const userId=Number(p[1]);const amount=Number(String(p[2]||'').replace(',','.'));if(!userId||!Number.isFinite(amount)||amount===0)return ctx.reply('Użycie: /balance ID +50 lub /balance ID -20');const r=await adjustBalance(userId,Math.round(amount*100),'admin command');if(!r)return ctx.reply('Nie znaleziono użytkownika.');await ctx.reply(`✅ Saldo użytkownika ${userId}: ${money(r.balance_cents)}`);try{await bot.api.sendMessage(userId,`💰 *Zmiana salda*\n\n${amount>0?'+':''}${amount.toFixed(2).replace('.',',')} zł\nNowe saldo: *${money(r.balance_cents)}*`,{parse_mode:'Markdown'});}catch{}});

bot.catch(err=>console.error('La Familia bot error:',err.error||err));
